from openpyxl import Workbook

from app.excel_common import write_metadata_block, style_header_row


def test_write_metadata_block_returns_correct_header_row_without_address():
    wb = Workbook()
    ws = wb.active
    header_row = write_metadata_block(ws, "Test Report", "RPT-2026-00001", "Test User", "All records")
    # row 1: company name, row 2: title, row 3: doc no/printed, row 4: generated by/filters, row 5: blank
    assert header_row == 6
    assert ws.cell(row=1, column=1).value == "Test Factory"
    assert ws.cell(row=2, column=1).value == "Test Report"
    assert "RPT-2026-00001" in ws.cell(row=3, column=1).value
    assert "Test User" in ws.cell(row=4, column=1).value


def test_write_metadata_block_includes_address_when_configured(monkeypatch):
    import app.excel_common as ec
    monkeypatch.setattr(ec, "COMPANY_ADDRESS", "123 Test Street")
    wb = Workbook()
    ws = wb.active
    header_row = write_metadata_block(ws, "Test Report", "RPT-2026-00001", "Test User", "All records")
    # with an address, everything shifts down one row
    assert ws.cell(row=2, column=1).value == "123 Test Street"
    assert ws.cell(row=3, column=1).value == "Test Report"
    assert header_row == 7


def test_write_metadata_block_bolds_company_name_and_title():
    wb = Workbook()
    ws = wb.active
    write_metadata_block(ws, "Test Report", "RPT-2026-00001", "Test User", "All records")
    assert ws.cell(row=1, column=1).font.bold is True
    assert ws.cell(row=2, column=1).font.bold is True


def test_style_header_row_applies_blue_fill_and_white_bold_font():
    wb = Workbook()
    ws = wb.active
    ws.append(["Col A", "Col B", "Col C"])
    style_header_row(ws, 1)
    for cell in ws[1]:
        assert cell.font.bold is True
        assert cell.font.color.rgb == "00FFFFFF"
        assert cell.fill.start_color.rgb == "001D4ED8"
