"""Shared Excel building blocks, used by any program that generates
spreadsheet exports.

Mirrors app/pdf_common.py's role for PDFs: the document-metadata block
(company name/address, title, pre-numbered document reference, who
generated it and when) and the standard header-row styling are the same
across every export this app produces. Originally this was written twice,
once in app/programs/expenses/services/reports.py and once in
app/services/audit.py, byte-for-byte identical except for the sheet title -
extracted here once a duplication check found it.

Depends on: openpyxl, app.config (company name/address) - nothing
program-specific.
Used by: app.programs.expenses.services.reports, app.services.audit.
"""
from datetime import datetime

from openpyxl.styles import Font, PatternFill

from app.config import COMPANY_NAME, COMPANY_ADDRESS

__all__ = ["write_metadata_block", "style_header_row"]


def write_metadata_block(ws, title, document_no, generated_by, filters_description):
    """Writes the standard metadata block at the top of a worksheet: company
    name (+ address if configured), the document title, document number,
    print time, who generated it, and the active filters. Returns the row
    number the column headers should start on."""
    meta = [[COMPANY_NAME]]
    if COMPANY_ADDRESS:
        meta.append([COMPANY_ADDRESS])
    meta.append([title])
    title_row = len(meta)
    meta += [
        [f"Document No: {document_no}", f"Printed on: {datetime.now().strftime('%Y-%m-%d %H:%M')}"],
        [f"Generated by: {generated_by}", filters_description],
        [],
    ]
    for row in meta:
        ws.append(row)
    ws.cell(row=1, column=1).font = Font(bold=True)
    ws.cell(row=title_row, column=1).font = Font(bold=True)
    return len(meta) + 1


def style_header_row(ws, row):
    """Applies the standard white-on-blue bold styling to a worksheet's
    column header row."""
    for cell in ws[row]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="1D4ED8", end_color="1D4ED8", fill_type="solid")
