"""Shared PDF building blocks, used by any program that generates PDFs.

Concern: (1) sandboxing - escaping untrusted text before it reaches
reportlab's markup-interpreting Paragraph class (see safe_text below), and
(2) the document conventions every PDF in this app follows: A4, a
pre-numbered header showing who generated it and when, and a matching
footer. A program-specific PDF module (like
app/programs/expenses/pdf_reports.py) imports document_header()/footer()
from here rather than reimplementing them, so every program's PDFs look and
behave the same without copy-pasting the styling.

Also home to build_audit_log_pdf(): the audit log is shared, system-wide
infrastructure (every program logs into the same audit_log table via
app.database.log_action), so its PDF export lives here rather than inside
any one program's package - exactly the kind of thing a future program
should be able to reuse without reaching into another program's files.

Depends on: reportlab, app.config (company name / currency) - nothing
program-specific.
Used by: app.programs.expenses.pdf_voucher, app.programs.expenses.pdf_reports,
app.services.audit.
"""
import io
from datetime import datetime
from xml.sax.saxutils import escape as _xml_escape

from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from app.config import COMPANY_NAME, COMPANY_ADDRESS, CURRENCY_SYMBOL

__all__ = [
    "safe_text", "money", "TITLE", "SUBTITLE", "ADDRESS", "META", "HEADCELL", "CELL", "TOTAL",
    "document_header", "footer", "standard_table_style", "build_audit_log_pdf",
]

styles = getSampleStyleSheet()
TITLE = ParagraphStyle("RTitle", parent=styles["Heading2"], alignment=1, spaceAfter=1)
SUBTITLE = ParagraphStyle("RSubtitle", parent=styles["Normal"], alignment=1,
                           textColor=colors.grey, fontSize=10, spaceAfter=6)
ADDRESS = ParagraphStyle("RAddress", parent=styles["Normal"], alignment=1,
                          textColor=colors.grey, fontSize=8.5, spaceAfter=6)
META = ParagraphStyle("RMeta", parent=styles["Normal"], fontSize=8.5, textColor=colors.grey)
HEADCELL = ParagraphStyle("HeadCell", parent=styles["Normal"], fontSize=8, textColor=colors.white,
                           fontName="Helvetica-Bold")
CELL = ParagraphStyle("Cell", parent=styles["Normal"], fontSize=8)
TOTAL = ParagraphStyle("Total", parent=styles["Normal"], fontSize=10, fontName="Helvetica-Bold")


def safe_text(value) -> str:
    """Escapes a value for safe inclusion in a reportlab Paragraph, which
    interprets a subset of XML/HTML-style markup. Untrusted, user-supplied
    strings (voucher particulars, names, audit log details, etc.) must
    always pass through this before being wrapped in Paragraph() - otherwise
    embedded tags are either silently interpreted as formatting markup or,
    for malformed tags, raise an unhandled exception that would break PDF
    generation for every voucher/report that includes the offending text."""
    if value is None:
        return ""
    return _xml_escape(str(value))


def money(value) -> str:
    try:
        return f"{CURRENCY_SYMBOL} {float(value):,.2f}"
    except (TypeError, ValueError):
        return str(value)


def document_header(title: str, document_no: str, generated_by: str,
                     filters_description: str) -> list:
    """The header block every report PDF starts with: company name, document
    title, pre-numbered document reference, who generated it, and when."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    story = [
        Paragraph(COMPANY_NAME, TITLE),
        Paragraph(safe_text(title), SUBTITLE),
    ]
    if COMPANY_ADDRESS:
        story.insert(1, Paragraph(safe_text(COMPANY_ADDRESS), ADDRESS))
    meta_rows = [
        [Paragraph(f"<b>Document No:</b> {safe_text(document_no)}", META),
         Paragraph(f"<b>Printed on:</b> {now}", META)],
        [Paragraph(f"<b>Generated by:</b> {safe_text(generated_by)}", META),
         Paragraph(f"<b>{safe_text(filters_description)}</b>", META)],
    ]
    meta_table = Table(meta_rows, colWidths=["50%", "50%"])
    meta_table.setStyle(TableStyle([
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 1),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 6 * mm))
    return story


def footer(document_no: str, program_name: str = ""):
    """Draws 'Document No [— Program] · Page X' at the bottom of every
    page. `program_name` is optional and omitted by default - pass it for
    a program-specific export (e.g. "Expense Program", "Weekly
    Productions"); leave it blank for shared/system-wide documents like
    the audit log, which isn't any one program's."""
    def _draw(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.grey)
        label = safe_text(document_no)
        if program_name:
            label += f" — {safe_text(program_name)}"
        canvas.drawString(doc.leftMargin, 12 * mm, label)
        canvas.drawRightString(
            doc.pagesize[0] - doc.rightMargin, 12 * mm, f"Page {canvas.getPageNumber()}"
        )
        canvas.restoreState()
    return _draw


def standard_table_style(*, zebra_end=-1, valign="TOP", extra=None):
    """The TableStyle rules every data table in this app's PDFs shares: a
    black header row, alternating white/whitesmoke body rows, and
    consistent cell padding. Found duplicated 5 times (with small
    variations) across pdf_common.py, pdf_voucher.py, and pdf_reports.py
    by a duplication check; this is the one place that pattern is defined
    now, with parameters for the real differences that existed:
      zebra_end - pass -2 instead of -1 to exclude a trailing totals row
                  from the zebra stripe
      valign    - pass None to omit vertical alignment entirely, or a
                  different value ("MIDDLE") than the TOP default
      extra     - additional rules (e.g. LINEBELOW) appended on top
    Returns a plain list, not a TableStyle - wrap it yourself:
    TableStyle(standard_table_style(...)).
    """
    rules = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.black),
        ("ROWBACKGROUNDS", (0, 1), (-1, zebra_end), [colors.white, colors.whitesmoke]),
        ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]
    if valign:
        rules.append(("VALIGN", (0, 0), (-1, -1), valign))
    if extra:
        rules += extra
    return rules


def build_audit_log_pdf(entries, *, document_no, generated_by, filters_description):
    """A4 landscape listing of audit log entries - shared/system-wide, not
    tied to any one program's data."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4), pageCompression=0,
        topMargin=15 * mm, bottomMargin=18 * mm, leftMargin=15 * mm, rightMargin=15 * mm,
    )
    story = document_header("Audit Log", document_no, generated_by, filters_description)

    headers = ["When", "User", "Action", "Details"]
    data = [[Paragraph(h, HEADCELL) for h in headers]]
    for e in entries:
        data.append([
            Paragraph(safe_text(e["created_at"]), CELL), Paragraph(safe_text(e.get("full_name") or "system"), CELL),
            Paragraph(safe_text(e["action"]), CELL), Paragraph(safe_text((e.get("details") or "")[:120]), CELL),
        ])
    table = Table(data, colWidths=[35 * mm, 40 * mm, 45 * mm, 147 * mm], repeatRows=1)
    table.setStyle(TableStyle(standard_table_style()))
    story.append(table)
    if not entries:
        story.append(Spacer(1, 6 * mm))
        story.append(Paragraph("No audit entries match the selected filters.", META))

    doc.build(story, onFirstPage=footer(document_no), onLaterPages=footer(document_no))
    return buf.getvalue()
